# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- feature/azure-pipelines-docker

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Maven_Build
  displayName: Build jar
  jobs:
  - job: Build
    displayName: Build jar
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        goals: 'package -DskipTests'
        
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Docker_Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'